coverage:
  precision: 2
  round: down
  range: "63...100"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  after_n_builds: 17